



portals=['Myntra','Nykaa']

username="90northbrands"
password="90northbrands"





[passwords]
    90northbrands = "90northbrands"


[connections.gsheets]
    spreadsheet = "https://docs.google.com/spreadsheets/d/1tQNhyQZexb4IJEXsBYbl78mNSsT85a3OfAY5Yh53lUo/edit?usp=sharing"
    worksheet = "<worksheet-gid-or-folder-id>"  # worksheet GID is used when using Public Spreadsheet URL, when usign service_account it will be picked as folder_id
    type = "service_account"  # leave empty when using Public Spreadsheet URL, when using service_account -> type = "service_account"
    project_id = "gsheets-90northbrands"
    private_key_id = "5dec37fb0fc0ece602a74a0035c0f21e6e311030"
    private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDiESP7cyPakpIe\n246Oduu3IBAyIUa7gEhzrNzhM3KG6q1Bx+TVE9FyXOfkDtVzuiR+n9Zq+DKirtiI\nrbc5S8Os4NZSqPiy7GreU4lDa6Sez/FUqERLb6oAAXnY1vQVPj78BDmOAM3CK3BF\n8bXYWdI/b64EVozCk9U3CGsMyzrJz8LwwA2atUNaQBGpc4aFWILWJZeErAtsF/Ua\nk40cV2feysWlWPIoolOoLhUt/DGzDDsFLfQG6Dl4a6vpiO4mKR+ueBP+mq7ZT+7m\nZxPCHDj5ouGRS+RirwkGlX0S/b1jldWUDQVhlmpxdTr/68mK3BRWsyZkq1ZdiwkW\n7lhkAGuPAgMBAAECggEADIwiAKNX4ppPBOpvw6WDGMNtUrL5H5ATtWPrUI6P9UAS\nRLvpDhCPB/dzIXvXShiTTPnnJ0HGYbQtrYxixonXfwFts+HQB/JKTjO5wyW22d+1\nx9qdC8jTWTO7xRbNLl6plUhQv3p48SWDEkbDrpHxsvaqZHA/WM9mvqq3clrXVPsZ\n37dMe20SehzX27uG3dYoJokTwAQ01AotLDCfJq88GlwUz15GECr1liYVCWk5D+0z\nGlx/jOeyxYUfx2qlKqkUGoKg6DRtmg1iLk+Y7Lga/wZ9R1WBS+fLS/7JRAc0Iug/\nsjHJmg/kUnAP1ZrNpCH7I14WwoGiJMvekXlcrY+/YQKBgQD6EIi7E6Gl3r4/kgi8\nJuyd6XiOT64zxg4ya2dc2gzIcap1wz2baeU/ot6pHqcY+At4LxMACdtNpDxMhbEX\n11ceJ36zR8DGnN3UiGDOXoTL7M3Jr17pDiQiVOjTmv86XgU9NGXJSW4EGMsJURIb\n96h7FRoq1jEjLPcG04Pp/ac0bwKBgQDnbsov9MrH30fUy7LQv2aU5CTnoU5vpdOf\n9k3XI4tZrM4rQUmC+1Ucq2z3wr4sP/a66h7mhJS9Axltx4n1QLE59tLaBcGs8auM\n2847y5urL0iP7LVxv165hrPtgIwZzH8QVkJKtVj4AXCACYXOKh5cUc3B1wJn8Wm4\nn6+sKXEK4QKBgQD3RYQ/ITF2GKUdrWUP0JmnqOc6KhaDQbRmLQh/q2p6htNdMZvo\n4zT60S3GI/Zt3VFSHZJ3NkfyJZYuwQCWJ60Qt1M1Kp24iANfFyBK0PIVyGrRpaV/\nZSlb/YRhQmJhL/mURQzllsPAL1gONWln2GR0mTBP7Y+XTe5ThLJrnhRJ5wKBgQCP\ntuvVVeTqs0vO5+OV35WbFgWY1UF48Xf2GKSD2a26NSYeFD/LF7nlwMo9HPCtV9cm\ngSZJLcGTki4jTsrrwo2LmiubegGoHLbUFNb/qNN1PTqJLYwLI7R17yEidjYJ+0RY\nZ8hozi5+a55p1AAEY4FRAPeNzK/QzkhBfuA/P8jT4QKBgArLdiwve20vfW+Zogyn\nz5RQT/vQVUN/xP2wpseTls27GE9YCtSiL4PEHu/AxqyZMkLcQAuOShe8936p8ktu\nTeHHyIIkV0OqphlsKYbLPkhqswhxIXHfRb/cpSS8dNqpBucOEQvAewTAXA7u4VBR\nnS4GeI7QynjMdkQUYUQdEiwr\n-----END PRIVATE KEY-----\n"
    client_email = "myntra-sales-analysis@gsheets-90northbrands.iam.gserviceaccount.com"
    client_id = "101278854877044633677"
    auth_uri = "https://accounts.google.com/o/oauth2/auth"
    token_uri = "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/myntra-sales-analysis%40gsheets-90northbrands.iam.gserviceaccount.com"



